// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Node interface {
	IsNode()
	GetID() string
}

type Address struct {
	ID        string `json:"id"`
	UserID    string `json:"userId"`
	Label     string `json:"label"`
	Street    string `json:"street"`
	City      string `json:"city"`
	State     string `json:"state"`
	ZipCode   string `json:"zipCode"`
	Country   string `json:"country"`
	IsDefault bool   `json:"isDefault"`
}

func (Address) IsNode()            {}
func (this Address) GetID() string { return this.ID }

type AddressInput struct {
	Label     string `json:"label"`
	Street    string `json:"street"`
	City      string `json:"city"`
	State     string `json:"state"`
	ZipCode   string `json:"zipCode"`
	Country   string `json:"country"`
	IsDefault *bool  `json:"isDefault,omitempty"`
}

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user,omitempty"`
	ExpiresIn    *int   `json:"expiresIn,omitempty"`
}

type CategoryConnection struct {
	Edges    []*CategoryEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type CategoryEdge struct {
	Node   *Category `json:"node"`
	Cursor string    `json:"cursor"`
}

type CreateCategoryInput struct {
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description *string         `json:"description,omitempty"`
	ParentID    *string         `json:"parentId,omitempty"`
	SortOrder   int             `json:"SortOrder"`
	IsActive    bool            `json:"IsActive"`
	Image       *graphql.Upload `json:"image,omitempty"`
}

type CreateProductInput struct {
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Price            float64         `json:"price"`
	Sku              string          `json:"sku"`
	Stock            int             `json:"stock"`
	CategoryID       string          `json:"categoryId"`
	Image            *graphql.Upload `json:"image,omitempty"`
	Slug             string          `json:"slug"`
	ShortDescription *string         `json:"shortDescription,omitempty"`
	Brand            *string         `json:"brand,omitempty"`
	Tags             []string        `json:"tags,omitempty"`
	Attributes       *string         `json:"attributes,omitempty"`
	Status           *string         `json:"status,omitempty"`
	VendorID         *string         `json:"vendorId,omitempty"`
}

type CreateVariantInput struct {
	ProductID      string          `json:"productId"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Options        *string         `json:"options,omitempty"`
	Price          float64         `json:"price"`
	CompareAtPrice *float64        `json:"compareAtPrice,omitempty"`
	CostPrice      *float64        `json:"costPrice,omitempty"`
	WeightGrams    int             `json:"weightGrams"`
	Image          *graphql.Upload `json:"image,omitempty"`
	IsActive       bool            `json:"isActive"`
}

type HealthCheck struct {
	Status    string           `json:"status"`
	Timestamp time.Time        `json:"timestamp"`
	Services  []*ServiceHealth `json:"services"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	TotalCount      int     `json:"totalCount"`
}

type PaginationInput struct {
	First  *int    `json:"first,omitempty"`
	After  *string `json:"after,omitempty"`
	Last   *int    `json:"last,omitempty"`
	Before *string `json:"before,omitempty"`
}

type ProductConnection struct {
	Edges    []*ProductEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ProductEdge struct {
	Node   *Product `json:"node"`
	Cursor string   `json:"cursor"`
}

type Query struct {
}

type RegisterInput struct {
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     *string `json:"phone,omitempty"`
}

type ServiceHealth struct {
	Name    string `json:"name"`
	Status  string `json:"status"`
	Latency *int   `json:"latency,omitempty"`
}

type SigninInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateCategoryInput struct {
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description *string         `json:"description,omitempty"`
	ParentID    *string         `json:"parentId,omitempty"`
	SortOrder   int             `json:"sortOrder"`
	IsActive    bool            `json:"isActive"`
	Image       *graphql.Upload `json:"image,omitempty"`
}

type UpdateProductInput struct {
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Price            float64         `json:"price"`
	Sku              string          `json:"sku"`
	Stock            int             `json:"stock"`
	CategoryID       string          `json:"categoryId"`
	Image            *graphql.Upload `json:"image,omitempty"`
	Slug             string          `json:"slug"`
	ShortDescription *string         `json:"shortDescription,omitempty"`
	Brand            *string         `json:"brand,omitempty"`
	Tags             []string        `json:"tags,omitempty"`
	Attributes       *string         `json:"attributes,omitempty"`
	Status           *string         `json:"status,omitempty"`
}

type UpdateProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}

type UpdateVariantInput struct {
	ProductID      string          `json:"productId"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Options        *string         `json:"options,omitempty"`
	Price          float64         `json:"price"`
	CompareAtPrice *float64        `json:"compareAtPrice,omitempty"`
	CostPrice      *float64        `json:"costPrice,omitempty"`
	WeightGrams    int             `json:"weightGrams"`
	Image          *graphql.Upload `json:"image,omitempty"`
	IsActive       bool            `json:"isActive"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}

type Variant struct {
	ID             string    `json:"id"`
	ProductID      string    `json:"productId"`
	Sku            string    `json:"sku"`
	Name           string    `json:"name"`
	Options        *string   `json:"options,omitempty"`
	Price          float64   `json:"price"`
	CompareAtPrice *float64  `json:"compareAtPrice,omitempty"`
	CostPrice      *float64  `json:"costPrice,omitempty"`
	WeightGrams    int       `json:"weightGrams"`
	ImageURL       *string   `json:"imageUrl,omitempty"`
	IsActive       bool      `json:"isActive"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

func (Variant) IsNode()            {}
func (this Variant) GetID() string { return this.ID }

type Role string

const (
	RoleCustomer Role = "customer"
	RoleAdmin    Role = "admin"
)

var AllRole = []Role{
	RoleCustomer,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleCustomer, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
