package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	userpb "github.com/manojnegi/ecomm-microservices/gen/go/user/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Auth mutations
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.Register(ctx, &userpb.RegisterRequest{
		Email:     input.Email,
		Password:  input.Password,
		FirstName: input.FirstName,
		LastName:  input.LastName,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.SigninInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.Login(ctx, &userpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// AdminLogin is the resolver for the adminLogin field.
func (r *mutationResolver) AdminLogin(ctx context.Context, input model.SigninInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.AdminLogin(ctx, &userpb.AdminLoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.RefreshToken(ctx, &userpb.RefreshTokenRequest{
		RefreshToken: token,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	_, err := r.UserClient.Auth.Logout(ctx, &userpb.LogoutRequest{
		RefreshToken: "",
	})
	return err == nil, err
}

// User Profile mutations
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	req := &userpb.UpdateProfileRequest{UserId: userID.(string)}
	if input.FirstName != nil {
		req.FirstName = *input.FirstName
	}
	if input.LastName != nil {
		req.LastName = *input.LastName
	}

	resp, err := r.UserClient.User.UpdateProfile(ctx, req)
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// Addresses mutations
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.AddressInput) (*model.Address, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	resp, err := r.UserClient.Addr.CreateAddress(ctx, &userpb.CreateAddressRequest{
		UserId:      userID.(string),
		Label:       input.Label,
		Line1:       input.Street,
		City:        input.City,
		State:       input.State,
		PostalCode:  input.ZipCode,
		CountryCode: input.Country,
		IsDefault:   input.IsDefault != nil && *input.IsDefault,
	})
	if err != nil {
		return nil, err
	}
	return mapAddressFromProto(resp), nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, id string, input model.AddressInput) (*model.Address, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	resp, err := r.UserClient.Addr.UpdateAddress(ctx, &userpb.UpdateAddressRequest{
		AddressId:   id,
		UserId:      userID.(string),
		Label:       input.Label,
		Line1:       input.Street,
		City:        input.City,
		State:       input.State,
		PostalCode:  input.ZipCode,
		CountryCode: input.Country,
		IsDefault:   input.IsDefault != nil && *input.IsDefault,
	})
	if err != nil {
		return nil, err
	}
	return mapAddressFromProto(resp), nil
}

// DeleteAddress is the resolver for the deleteAddress field.
func (r *mutationResolver) DeleteAddress(ctx context.Context, id string) (bool, error) {
	_, err := r.UserClient.Addr.DeleteAddress(ctx, &userpb.DeleteAddressRequest{
		AddressId: id,
	})
	return err == nil, err
}

// SetDefaultAddress is the resolver for the setDefaultAddress field.
func (r *mutationResolver) SetDefaultAddress(ctx context.Context, id string) (*model.Address, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	_, err = r.UserClient.Addr.SetDefaultAddress(ctx, &userpb.SetDefaultAddressRequest{
		UserId:    userID.(string),
		AddressId: id,
	})
	if err != nil {
		return nil, err
	}
	return &model.Address{ID: id, IsDefault: true}, nil
}

// Admin mutations
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id string, status model.UserStatus) (*model.User, error) {
	resp, err := r.UserClient.User.UpdateUserStatus(ctx, &userpb.UpdateUserStatusRequest{
		UserId: id,
		Status: mapStatusToProto(status),
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	_, err := r.UserClient.User.DeleteUser(ctx, &userpb.DeleteUserRequest{UserId: id})
	return err == nil, err
}

// Admin - Products mutations
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	req := &productpb.CreateProductRequest{
		CategoryId:       input.CategoryID,
		Name:             input.Name,
		Description:      input.Description,
		Slug:             input.Slug,
		ShortDescription: stringValue(input.ShortDescription),
		Brand:            stringValue(input.Brand),
		BrandId:          stringValue(input.BrandID),
		Tags:             input.Tags,
		Attributes:       stringValue(input.Attributes),
		Status:           stringValue(input.Status),
		VendorId:         stringValue(input.VendorID),
	}

	if input.Variants != nil {
		var pbVariants []*productpb.Variant
		for _, v := range input.Variants {
			pbVariant := &productpb.Variant{
				Sku:         v.Sku,
				Name:        v.Name,
				Options:     stringValue(v.Options),
				Price:       v.Price,
				WeightGrams: int32(v.WeightGrams),
				IsActive:    v.IsActive,
			}
			if v.InitialStock != nil {
				pbVariant.InitialStock = int32(*v.InitialStock)
			}
			if v.ID != nil {
				pbVariant.Id = *v.ID
			}
			if v.CompareAtPrice != nil {
				pbVariant.CompareAtPrice = *v.CompareAtPrice
			}
			if v.CostPrice != nil {
				pbVariant.CostPrice = *v.CostPrice
			}

			if v.Images != nil {
				var pbImages []*productpb.VariantImage
				for i, imgUpload := range v.Images {
					if imgUpload != nil {
						content, err := io.ReadAll(imgUpload.File)
						if err != nil {
							return nil, fmt.Errorf("failed to read variant upload file: %w", err)
						}

						key := fmt.Sprintf("variants/%d-%s", time.Now().UnixNano(), imgUpload.Filename)
						_, err = r.S3Storage.UploadFile(ctx, key, content, imgUpload.ContentType)
						if err != nil {
							return nil, fmt.Errorf("failed to upload variant image to S3: %w", err)
						}

						pbImages = append(pbImages, &productpb.VariantImage{
							Url:       key,
							SortOrder: int32(i),
						})
					}
				}
				pbVariant.Images = pbImages
			}

			pbVariants = append(pbVariants, pbVariant)
		}
		req.Variants = pbVariants
	}

	resp, err := r.ProductClient.Product.CreateProduct(ctx, req)
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	return mapProductFromProto(resp.Product, baseURL), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	req := &productpb.UpdateProductRequest{
		Id:               id,
		CategoryId:       input.CategoryID,
		Name:             input.Name,
		Description:      input.Description,
		Slug:             input.Slug,
		ShortDescription: stringValue(input.ShortDescription),
		Brand:            stringValue(input.Brand),
		BrandId:          stringValue(input.BrandID),
		Tags:             input.Tags,
		Attributes:       stringValue(input.Attributes),
		Status:           stringValue(input.Status),
		UpdateVariants:   input.Variants != nil,
	}

	if input.Variants != nil {
		var pbVariants []*productpb.Variant
		for _, v := range input.Variants {
			pbVariant := &productpb.Variant{
				Sku:         v.Sku,
				Name:        v.Name,
				Options:     stringValue(v.Options),
				Price:       v.Price,
				WeightGrams: int32(v.WeightGrams),
				IsActive:    v.IsActive,
			}
			if v.InitialStock != nil {
				pbVariant.InitialStock = int32(*v.InitialStock)
			}
			if v.ID != nil {
				pbVariant.Id = *v.ID
			}
			if v.CompareAtPrice != nil {
				pbVariant.CompareAtPrice = *v.CompareAtPrice
			}
			if v.CostPrice != nil {
				pbVariant.CostPrice = *v.CostPrice
			}

			if v.Images != nil {
				var pbImages []*productpb.VariantImage
				for i, imgUpload := range v.Images {
					if imgUpload != nil {
						content, err := io.ReadAll(imgUpload.File)
						if err != nil {
							return nil, fmt.Errorf("failed to read variant upload file: %w", err)
						}

						key := fmt.Sprintf("variants/%d-%s", time.Now().UnixNano(), imgUpload.Filename)
						_, err = r.S3Storage.UploadFile(ctx, key, content, imgUpload.ContentType)
						if err != nil {
							return nil, fmt.Errorf("failed to upload variant image to S3: %w", err)
						}

						pbImages = append(pbImages, &productpb.VariantImage{
							Url:       key,
							SortOrder: int32(i),
						})
					}
				}
				pbVariant.Images = pbImages
			}

			pbVariants = append(pbVariants, pbVariant)
		}
		req.Variants = pbVariants
	}

	resp, err := r.ProductClient.Product.UpdateProduct(ctx, req)
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	return mapProductFromProto(resp.Product, baseURL), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	resp, err := r.ProductClient.Product.DeleteProduct(ctx, &productpb.DeleteProductRequest{
		Id: id,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	var parentID string
	if input.ParentID != nil {
		parentID = *input.ParentID
	}

	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	var imageURL string
	if input.Image != nil {
		content, err := io.ReadAll(input.Image.File)
		if err != nil {
			return nil, fmt.Errorf("failed to read upload file: %w", err)
		}

		key := fmt.Sprintf("categories/%d-%s", time.Now().Unix(), input.Image.Filename)
		_, err = r.S3Storage.UploadFile(ctx, key, content, input.Image.ContentType)
		if err != nil {
			return nil, fmt.Errorf("failed to upload to S3: %w", err)
		}
		imageURL = key
	}

	resp, err := r.ProductClient.Category.CreateCategory(ctx, &productpb.CreateCategoryRequest{
		Name:        input.Name,
		Slug:        input.Slug,
		Description: description,
		ParentId:    parentID,
		ImageUrl:    imageURL,
		SortOrder:   int32(input.SortOrder),
		IsActive:    input.IsActive,
	})
	if err != nil {
		return nil, err
	}

	getResp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{Id: resp.Id})
	if err != nil {
		return &model.Category{ID: resp.Id, Name: input.Name}, nil
	}

	baseURL := r.S3Storage.GetBaseURL()
	return mapCategoryFromProto(getResp.Category, baseURL), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategoryInput) (*model.Category, error) {
	// Get existing category first
	existing, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{Id: id})
	if err != nil {
		return nil, fmt.Errorf("category not found: %w", err)
	}

	var parentID string
	if input.ParentID != nil {
		parentID = *input.ParentID
	}

	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	imageURL := existing.Category.ImageUrl
	if input.Image != nil {
		content, err := io.ReadAll(input.Image.File)
		if err != nil {
			return nil, fmt.Errorf("failed to read upload file: %w", err)
		}

		key := fmt.Sprintf("categories/%d-%s", time.Now().Unix(), input.Image.Filename)
		_, err = r.S3Storage.UploadFile(ctx, key, content, input.Image.ContentType)
		if err != nil {
			return nil, fmt.Errorf("failed to upload to S3: %w", err)
		}
		imageURL = key
	}

	resp, err := r.ProductClient.Category.UpdateCategory(ctx, &productpb.UpdateCategoryRequest{
		Id:          id,
		Name:        input.Name,
		Slug:        input.Slug,
		Description: description,
		ParentId:    parentID,
		ImageUrl:    imageURL,
		SortOrder:   int32(input.SortOrder),
		IsActive:    input.IsActive,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	return mapCategoryFromProto(resp.Category, baseURL), nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	resp, err := r.ProductClient.Category.DeleteCategory(ctx, &productpb.DeleteCategoryRequest{
		Id: id,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// CreateVariant is the resolver for the createVariant field.
func (r *mutationResolver) CreateVariant(ctx context.Context, input model.CreateVariantInput) (*model.Variant, error) {
	var imageURL string
	if input.Image != nil {
		content, err := io.ReadAll(input.Image.File)
		if err != nil {
			return nil, fmt.Errorf("failed to read upload file: %w", err)
		}

		key := fmt.Sprintf("variants/%d-%s", time.Now().Unix(), input.Image.Filename)
		_, err = r.S3Storage.UploadFile(ctx, key, content, input.Image.ContentType)
		if err != nil {
			return nil, fmt.Errorf("failed to upload to S3: %w", err)
		}
		imageURL = key
	}

	resp, err := r.ProductClient.Product.CreateVariant(ctx, &productpb.CreateVariantRequest{
		ProductId:      input.ProductID,
		Sku:            input.Sku,
		Name:           input.Name,
		Options:        stringValue(input.Options),
		Price:          input.Price,
		CompareAtPrice: floatValue(input.CompareAtPrice),
		CostPrice:      floatValue(input.CostPrice),
		WeightGrams:    int32(input.WeightGrams),
		InitialStock:   int32(intValue(input.InitialStock)),
		ImageUrl:       imageURL,
		IsActive:       input.IsActive,
	})
	if err != nil {
		return nil, err
	}

	return mapVariantFromProto(resp.Variant, r.S3Storage.GetBaseURL()), nil
}

// UpdateVariant is the resolver for the updateVariant field.
func (r *mutationResolver) UpdateVariant(ctx context.Context, id string, input model.UpdateVariantInput) (*model.Variant, error) {
	var imageURL string
	if input.Image != nil {
		content, err := io.ReadAll(input.Image.File)
		if err != nil {
			return nil, fmt.Errorf("failed to read upload file: %w", err)
		}

		key := fmt.Sprintf("variants/%d-%s", time.Now().Unix(), input.Image.Filename)
		_, err = r.S3Storage.UploadFile(ctx, key, content, input.Image.ContentType)
		if err != nil {
			return nil, fmt.Errorf("failed to upload to S3: %w", err)
		}
		imageURL = key
	}

	resp, err := r.ProductClient.Product.UpdateVariant(ctx, &productpb.UpdateVariantRequest{
		Id:             id,
		ProductId:      input.ProductID,
		Sku:            input.Sku,
		Name:           input.Name,
		Options:        stringValue(input.Options),
		Price:          input.Price,
		CompareAtPrice: floatValue(input.CompareAtPrice),
		CostPrice:      floatValue(input.CostPrice),
		WeightGrams:    int32(input.WeightGrams),
		InitialStock:   int32(intValue(input.InitialStock)),
		ImageUrl:       imageURL, // Missing logic to retain existing image if not provided, but simplified for now
		IsActive:       input.IsActive,
	})
	if err != nil {
		return nil, err
	}

	return mapVariantFromProto(resp.Variant, r.S3Storage.GetBaseURL()), nil
}

// DeleteVariant is the resolver for the deleteVariant field.
func (r *mutationResolver) DeleteVariant(ctx context.Context, id string) (bool, error) {
	resp, err := r.ProductClient.Product.DeleteVariant(ctx, &productpb.DeleteVariantRequest{
		Id: id,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// UpdateInventory is the resolver for the updateInventory field.
func (r *mutationResolver) UpdateInventory(ctx context.Context, variantID string, input model.UpdateInventoryInput) (*model.Inventory, error) {
	resp, err := r.ProductClient.Inventory.UpdateInventory(ctx, &productpb.UpdateInventoryRequest{
		VariantId:      variantID,
		QuantityOnHand: int32(input.QuantityOnHand),
		ReorderPoint:   int32(input.ReorderPoint),
	})
	if err != nil {
		return nil, err
	}

	return &model.Inventory{
		VariantID:         resp.Inventory.VariantId,
		QuantityOnHand:    int(resp.Inventory.QuantityOnHand),
		QuantityReserved:  int(resp.Inventory.QuantityReserved),
		QuantityAvailable: int(resp.Inventory.QuantityAvailable),
		ReorderPoint:      int(resp.Inventory.ReorderPoint),
	}, nil
}

// AddVariantImage is the resolver for the addVariantImage field.
func (r *mutationResolver) AddVariantImage(ctx context.Context, variantID string, url string, altText *string, sortOrder *int) (*model.VariantImage, error) {
	altTxt := ""
	if altText != nil {
		altTxt = *altText
	}
	order := int32(0)
	if sortOrder != nil {
		order = int32(*sortOrder)
	}

	resp, err := r.ProductClient.Product.AddVariantImage(ctx, &productpb.AddVariantImageRequest{
		VariantId: variantID,
		Url:       url,
		AltText:   altTxt,
		SortOrder: order,
	})
	if err != nil {
		return nil, err
	}

	createdAt, _ := time.Parse(time.RFC3339, resp.Image.CreatedAt)
	imgUrl := resp.Image.Url
	baseURL := r.S3Storage.GetBaseURL()
	if imgUrl != "" && !strings.HasPrefix(imgUrl, "http") {
		imgUrl = baseURL + imgUrl
	}

	var altTextPtr *string
	if resp.Image.AltText != "" {
		altTextPtr = &resp.Image.AltText
	}

	return &model.VariantImage{
		ID:        resp.Image.Id,
		VariantID: resp.Image.VariantId,
		URL:       imgUrl,
		AltText:   altTextPtr,
		SortOrder: int(resp.Image.SortOrder),
		CreatedAt: createdAt,
	}, nil
}

// RemoveVariantImage is the resolver for the removeVariantImage field.
func (r *mutationResolver) RemoveVariantImage(ctx context.Context, id string) (bool, error) {
	resp, err := r.ProductClient.Product.RemoveVariantImage(ctx, &productpb.RemoveVariantImageRequest{
		Id: id,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// ReorderVariantImages is the resolver for the reorderVariantImages field.
func (r *mutationResolver) ReorderVariantImages(ctx context.Context, variantID string, orders []*model.ImageOrderInput) (bool, error) {
	var pbOrders []*productpb.ImageOrder
	for _, o := range orders {
		pbOrders = append(pbOrders, &productpb.ImageOrder{
			Id:        o.ID,
			SortOrder: int32(o.SortOrder),
		})
	}

	resp, err := r.ProductClient.Product.ReorderVariantImages(ctx, &productpb.ReorderVariantImagesRequest{
		VariantId: variantID,
		Images:    pbOrders,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
