package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	userpb "github.com/manojnegi/ecomm-microservices/gen/go/user/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Auth mutations
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.Register(ctx, &userpb.RegisterRequest{
		Email:     input.Email,
		Password:  input.Password,
		FirstName: input.FirstName,
		LastName:  input.LastName,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.SigninInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.Login(ctx, &userpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// AdminLogin is the resolver for the adminLogin field.
func (r *mutationResolver) AdminLogin(ctx context.Context, input model.SigninInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.AdminLogin(ctx, &userpb.AdminLoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         mapUserFromProto(resp.User),
		ExpiresIn:    intPtr(int(resp.ExpiresAt)),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Auth.RefreshToken(ctx, &userpb.RefreshTokenRequest{
		RefreshToken: token,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	_, err := r.UserClient.Auth.Logout(ctx, &userpb.LogoutRequest{
		RefreshToken: "",
	})
	return err == nil, err
}

// User Profile mutations
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	req := &userpb.UpdateProfileRequest{UserId: userID.(string)}
	if input.FirstName != nil {
		req.FirstName = *input.FirstName
	}
	if input.LastName != nil {
		req.LastName = *input.LastName
	}

	resp, err := r.UserClient.User.UpdateProfile(ctx, req)
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// Addresses mutations
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.AddressInput) (*model.Address, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	resp, err := r.UserClient.Addr.CreateAddress(ctx, &userpb.CreateAddressRequest{
		UserId:      userID.(string),
		Label:       input.Label,
		Line1:       input.Street,
		City:        input.City,
		State:       input.State,
		PostalCode:  input.ZipCode,
		CountryCode: input.Country,
		IsDefault:   input.IsDefault != nil && *input.IsDefault,
	})
	if err != nil {
		return nil, err
	}
	return mapAddressFromProto(resp), nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, id string, input model.AddressInput) (*model.Address, error) {
	return nil, fmt.Errorf("UpdateAddress not implemented")
}

// DeleteAddress is the resolver for the deleteAddress field.
func (r *mutationResolver) DeleteAddress(ctx context.Context, id string) (bool, error) {
	_, err := r.UserClient.Addr.DeleteAddress(ctx, &userpb.DeleteAddressRequest{
		AddressId: id,
	})
	return err == nil, err
}

// SetDefaultAddress is the resolver for the setDefaultAddress field.
func (r *mutationResolver) SetDefaultAddress(ctx context.Context, id string) (*model.Address, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := gc.Get("userID")

	_, err = r.UserClient.Addr.SetDefaultAddress(ctx, &userpb.SetDefaultAddressRequest{
		UserId:    userID.(string),
		AddressId: id,
	})
	if err != nil {
		return nil, err
	}
	return &model.Address{ID: id, IsDefault: true}, nil
}

// Admin mutations
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id string, status model.UserStatus) (*model.User, error) {
	resp, err := r.UserClient.User.UpdateUserStatus(ctx, &userpb.UpdateUserStatusRequest{
		UserId: id,
		Status: mapStatusToProto(status),
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	_, err := r.UserClient.User.DeleteUser(ctx, &userpb.DeleteUserRequest{UserId: id})
	return err == nil, err
}

// Admin - Products mutations
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	return nil, fmt.Errorf("CreateProduct not implemented")
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	var parentID string
	if input.ParentID != nil {
		parentID = *input.ParentID
	}

	resp, err := r.ProductClient.Category.CreateCategory(ctx, &productpb.CreateCategoryRequest{
		Name:        input.Name,
		Slug:        input.Slug,
		Description: *input.Description,
		ParentId:    parentID,
	})
	if err != nil {
		return nil, err
	}

	getResp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{Id: resp.Id})
	if err != nil {
		return &model.Category{ID: resp.Id, Name: input.Name}, nil
	}

	return mapCategoryFromProto(getResp.Category), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
