package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Children is the resolver for the children field.
func (r *categoryResolver) Children(ctx context.Context, obj *model.Category) ([]*model.Category, error) {
	return []*model.Category{}, nil
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category) ([]*model.Product, error) {
	resp, err := r.ProductClient.Product.ListProducts(ctx, &productpb.ListProductsRequest{
		CategoryId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	products := make([]*model.Product, len(resp.Products))
	for i, p := range resp.Products {
		products[i] = mapProductFromProto(p, baseURL)
	}
	return products, nil
}

// Categories is the resolver for the categories field.
func (r *productResolver) Categories(ctx context.Context, obj *model.Product) ([]*model.Category, error) {
	var categories []*model.Category
	if len(obj.CategoryIDs) == 0 {
		return categories, nil
	}

	for _, catID := range obj.CategoryIDs {
		resp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{
			Id: catID,
		})
		if err != nil {
			// Skip or log error, but for now we continue
			fmt.Printf("Failed to get category %s: %v\n", catID, err)
			continue
		}

		var description, imageUrl, parentId *string
		if resp.Category.Description != "" {
			d := resp.Category.Description
			description = &d
		}
		if resp.Category.ImageUrl != "" {
			i := resp.Category.ImageUrl
			imageUrl = &i
		}
		if resp.Category.ParentId != "" {
			p := resp.Category.ParentId
			parentId = &p
		}

		categories = append(categories, &model.Category{
			ID:          resp.Category.Id,
			Name:        resp.Category.Name,
			Slug:        resp.Category.Slug,
			Description: description,
			ImageURL:    imageUrl,
			SortOrder:   int(resp.Category.SortOrder),
			IsActive:    resp.Category.IsActive,
			ParentID:    parentId,
		})
	}

	return categories, nil
}

// Inventory is the resolver for the inventory field.
func (r *variantResolver) Inventory(ctx context.Context, obj *model.Variant) (*model.Inventory, error) {
	resp, err := r.ProductClient.Inventory.GetInventory(ctx, &productpb.GetInventoryRequest{
		VariantId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	return &model.Inventory{
		VariantID:         resp.Inventory.VariantId,
		QuantityOnHand:    int(resp.Inventory.QuantityOnHand),
		QuantityReserved:  int(resp.Inventory.QuantityReserved),
		QuantityAvailable: int(resp.Inventory.QuantityAvailable),
		ReorderPoint:      int(resp.Inventory.ReorderPoint),
	}, nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Variant returns generated.VariantResolver implementation.
func (r *Resolver) Variant() generated.VariantResolver { return &variantResolver{r} }

type categoryResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type variantResolver struct{ *Resolver }
