package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Children is the resolver for the children field.
func (r *categoryResolver) Children(ctx context.Context, obj *model.Category) ([]*model.Category, error) {
	return []*model.Category{}, nil
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category) ([]*model.Product, error) {
	resp, err := r.ProductClient.Product.ListProducts(ctx, &productpb.ListProductsRequest{
		CategoryId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	products := make([]*model.Product, len(resp.Products))
	for i, p := range resp.Products {
		products[i] = mapProductFromProto(p, baseURL)
	}
	return products, nil
}

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *model.Product) (*model.Category, error) {
	resp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{
		Id: obj.CategoryID,
	})
	if err != nil {
		return nil, err
	}
	baseURL := r.S3Storage.GetBaseURL()
	return mapCategoryFromProto(resp.Category, baseURL), nil
}

// Brand is the resolver for the brand field.
func (r *productResolver) Brand(ctx context.Context, obj *model.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: Brand - brand"))
}

// BrandID is the resolver for the brandId field.
func (r *productResolver) BrandID(ctx context.Context, obj *model.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: BrandID - brandId"))
}

// Inventory is the resolver for the inventory field.
func (r *variantResolver) Inventory(ctx context.Context, obj *model.Variant) (*model.Inventory, error) {
	resp, err := r.ProductClient.Inventory.GetInventory(ctx, &productpb.GetInventoryRequest{
		VariantId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	return &model.Inventory{
		VariantID:         resp.Inventory.VariantId,
		QuantityOnHand:    int(resp.Inventory.QuantityOnHand),
		QuantityReserved:  int(resp.Inventory.QuantityReserved),
		QuantityAvailable: int(resp.Inventory.QuantityAvailable),
		ReorderPoint:      int(resp.Inventory.ReorderPoint),
	}, nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Variant returns generated.VariantResolver implementation.
func (r *Resolver) Variant() generated.VariantResolver { return &variantResolver{r} }

type categoryResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type variantResolver struct{ *Resolver }
