package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"
	"time"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	userpb "github.com/manojnegi/ecomm-microservices/gen/go/user/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Health
func (r *queryResolver) Health(ctx context.Context) (*model.HealthCheck, error) {
	return &model.HealthCheck{
		Status:    "healthy",
		Timestamp: time.Now(),
		Services: []*model.ServiceHealth{
			{Name: "api-gateway", Status: "up", Latency: intPtr(0)},
			{Name: "user-service", Status: "up", Latency: intPtr(0)},
			{Name: "product-service", Status: "up", Latency: intPtr(0)},
		},
	}, nil
}

// Inventories is the resolver for the inventories field.
func (r *queryResolver) Inventories(ctx context.Context, first *int, after *string) (*model.InventoryConnection, error) {
	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}

	// simple offset pagination for now, parsing "after" as offset
	offset := int32(0)
	// (Normally after would be parsed from base64, but using simple default 0 for this exercise unless we parse cursor properly)

	resp, err := r.ProductClient.Inventory.ListInventory(ctx, &productpb.ListInventoryRequest{
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model.InventoryEdge, len(resp.Inventories))
	for i, inv := range resp.Inventories {
		edges[i] = &model.InventoryEdge{
			Node: &model.Inventory{
				VariantID:         inv.VariantId,
				QuantityOnHand:    int(inv.QuantityOnHand),
				QuantityReserved:  int(inv.QuantityReserved),
				QuantityAvailable: int(inv.QuantityAvailable),
				ReorderPoint:      int(inv.ReorderPoint),
			},
			Cursor: encodeCursor(inv.VariantId),
		}
	}

	return &model.InventoryConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.TotalCount),
		},
	}, nil
}

// Auth/User queries
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, exists := gc.Get("userID")
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	resp, err := r.UserClient.User.GetUser(ctx, &userpb.GetUserRequest{
		UserId: userID.(string),
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.UserClient.User.GetUser(ctx, &userpb.GetUserRequest{
		UserId: id,
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *model.PaginationInput) (*model.UserConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	resp, err := r.UserClient.User.ListUsers(ctx, &userpb.ListUsersRequest{
		Page:     page,
		PageSize: pageSize,
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model.UserEdge, len(resp.Users))
	for i, u := range resp.Users {
		edges[i] = &model.UserEdge{
			Node:   mapUserFromProto(u),
			Cursor: encodeCursor(u.Id),
		}
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Products queries
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	resp, err := r.ProductClient.Product.GetProduct(ctx, &productpb.GetProductRequest{Id: id})
	if err != nil {
		return nil, err
	}
	baseURL := r.S3Storage.GetBaseURL()
	if len(resp.Product.Variants) > 0 {
		println("API GATEWAY GetProduct received variants:", len(resp.Product.Variants), "images in V[0]:", len(resp.Product.Variants[0].Images))
	}
	return mapProductFromProto(resp.Product, baseURL), nil
}

// ProductBySlug is the resolver for the productBySlug field.
func (r *queryResolver) ProductBySlug(ctx context.Context, slug string) (*model.Product, error) {
	resp, err := r.ProductClient.Product.GetProductBySlug(ctx, &productpb.GetProductBySlugRequest{Slug: slug})
	if err != nil {
		return nil, err
	}
	baseURL := r.S3Storage.GetBaseURL()
	return mapProductFromProto(resp.Product, baseURL), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, categoryID *string, filter *model.ProductFilterInput, sort *model.ProductSortInput, pagination *model.PaginationInput) (*model.ProductConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	var catID string
	if categoryID != nil {
		catID = *categoryID
	}
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	isAdmin := false
	gc, err := GinContextFromContext(ctx)
	if err == nil {
		if role, exists := gc.Get("role"); exists {
			if rStr, ok := role.(string); ok && strings.EqualFold(rStr, "admin") {
				isAdmin = true
			}
		}
	}

	req := &productpb.ListProductsRequest{
		CategoryId: catID,
		Page:       page,
		PageSize:   pageSize,
		IsAdmin:    isAdmin,
	}

	if filter != nil {
		if filter.MinPrice != nil {
			req.MinPrice = *filter.MinPrice
		}
		if filter.MaxPrice != nil {
			req.MaxPrice = *filter.MaxPrice
		}
		if len(filter.Brands) > 0 {
			req.Brands = filter.Brands
		}
	}

	if sort != nil {
		req.SortField = string(sort.Field)
		req.SortDirection = string(sort.Direction)
	}

	resp, err := r.ProductClient.Product.ListProducts(ctx, req)
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	edges := make([]*model.ProductEdge, len(resp.Products))
	for i, p := range resp.Products {
		edges[i] = &model.ProductEdge{
			Node:   mapProductFromProto(p, baseURL),
			Cursor: encodeCursor(p.Id),
		}
	}

	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, query string, pagination *model.PaginationInput) (*model.ProductConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	isAdmin := false
	gc, err := GinContextFromContext(ctx)
	if err == nil {
		if role, exists := gc.Get("role"); exists {
			if rStr, ok := role.(string); ok && strings.EqualFold(rStr, "admin") {
				isAdmin = true
			}
		}
	}

	resp, err := r.ProductClient.Product.SearchProducts(ctx, &productpb.SearchProductsRequest{
		Query:    query,
		Page:     page,
		PageSize: pageSize,
		IsAdmin:  isAdmin,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	edges := make([]*model.ProductEdge, len(resp.Products))
	for i, p := range resp.Products {
		edges[i] = &model.ProductEdge{
			Node:   mapProductFromProto(p, baseURL),
			Cursor: encodeCursor(p.Id),
		}
	}

	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, pagination *model.PaginationInput) (*model.CategoryConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	resp, err := r.ProductClient.Category.ListCategories(ctx, &productpb.ListCategoryRequest{
		Page:     page,
		PageSize: pageSize,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	edges := make([]*model.CategoryEdge, len(resp.Category))
	for i, c := range resp.Category {
		edges[i] = &model.CategoryEdge{
			Node:   mapCategoryFromProto(c, baseURL),
			Cursor: encodeCursor(c.Id),
		}
	}

	return &model.CategoryConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	resp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{Id: id})
	if err != nil {
		return nil, err
	}
	baseURL := r.S3Storage.GetBaseURL()
	return mapCategoryFromProto(resp.Category, baseURL), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
