package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	productpb "github.com/manojnegi/ecomm-microservices/gen/go/product/v1"
	userpb "github.com/manojnegi/ecomm-microservices/gen/go/user/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Health
func (r *queryResolver) Health(ctx context.Context) (*model.HealthCheck, error) {
	return &model.HealthCheck{
		Status:    "healthy",
		Timestamp: time.Now(),
		Services: []*model.ServiceHealth{
			{Name: "api-gateway", Status: "up", Latency: intPtr(0)},
			{Name: "user-service", Status: "up", Latency: intPtr(0)},
			{Name: "product-service", Status: "up", Latency: intPtr(0)},
		},
	}, nil
}

// Auth/User queries
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	gc, err := GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, exists := gc.Get("userID")
	if !exists {
		return nil, fmt.Errorf("unauthorized")
	}

	resp, err := r.UserClient.User.GetUser(ctx, &userpb.GetUserRequest{
		UserId: userID.(string),
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.UserClient.User.GetUser(ctx, &userpb.GetUserRequest{
		UserId: id,
	})
	if err != nil {
		return nil, err
	}
	return mapUserFromProto(resp), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *model.PaginationInput) (*model.UserConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	resp, err := r.UserClient.User.ListUsers(ctx, &userpb.ListUsersRequest{
		Page:     page,
		PageSize: pageSize,
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model.UserEdge, len(resp.Users))
	for i, u := range resp.Users {
		edges[i] = &model.UserEdge{
			Node:   mapUserFromProto(u),
			Cursor: encodeCursor(u.Id),
		}
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Products queries
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	return nil, fmt.Errorf("GetProduct not implemented")
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, categoryID *string, pagination *model.PaginationInput) (*model.ProductConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	var catID string
	if categoryID != nil {
		catID = *categoryID
	}
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	resp, err := r.ProductClient.Product.ListProducts(ctx, &productpb.ListProductsRequest{
		CategoryId: catID,
		Page:       page,
		PageSize:   pageSize,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	edges := make([]*model.ProductEdge, len(resp.Products))
	for i, p := range resp.Products {
		edges[i] = &model.ProductEdge{
			Node:   mapProductFromProto(p, baseURL),
			Cursor: encodeCursor(p.Id),
		}
	}

	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, pagination *model.PaginationInput) (*model.CategoryConnection, error) {
	page := int32(1)
	pageSize := int32(20)
	if pagination != nil && pagination.First != nil {
		pageSize = int32(*pagination.First)
	}

	resp, err := r.ProductClient.Category.ListCategories(ctx, &productpb.ListCategoryRequest{
		Page:     page,
		PageSize: pageSize,
	})
	if err != nil {
		return nil, err
	}

	baseURL := r.S3Storage.GetBaseURL()
	edges := make([]*model.CategoryEdge, len(resp.Category))
	for i, c := range resp.Category {
		edges[i] = &model.CategoryEdge{
			Node:   mapCategoryFromProto(c, baseURL),
			Cursor: encodeCursor(c.Id),
		}
	}

	return &model.CategoryConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			TotalCount:  int(resp.Total),
		},
	}, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	resp, err := r.ProductClient.Category.GetCategory(ctx, &productpb.GetCategoryRequest{Id: id})
	if err != nil {
		return nil, err
	}
	baseURL := r.S3Storage.GetBaseURL()
	return mapCategoryFromProto(resp.Category, baseURL), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
