package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	userpb "github.com/manojnegi/ecomm-microservices/gen/go/user/v1"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/generated"
	"github.com/manojnegi/ecommerce/api-gateway/internal/graphql/model"
)

// Addresses is the resolver for the addresses field.
func (r *userResolver) Addresses(ctx context.Context, obj *model.User) ([]*model.Address, error) {
	resp, err := r.UserClient.Addr.ListAddresses(ctx, &userpb.ListAddressesRequest{
		UserId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	addresses := make([]*model.Address, len(resp.Addresses))
	for i, a := range resp.Addresses {
		addresses[i] = mapAddressFromProto(a)
	}
	return addresses, nil
}

// DefaultAddress is the resolver for the defaultAddress field.
func (r *userResolver) DefaultAddress(ctx context.Context, obj *model.User) (*model.Address, error) {
	resp, err := r.UserClient.Addr.ListAddresses(ctx, &userpb.ListAddressesRequest{
		UserId: obj.ID,
	})
	if err != nil {
		return nil, err
	}

	for _, a := range resp.Addresses {
		if a.IsDefault {
			return mapAddressFromProto(a), nil
		}
	}
	return nil, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
