use deadpool_postgres::Pool;
use tonic::{Request, Response, Status};
use tracing::{error, info};
use uuid::Uuid;

use crate::proto::payment::{
    payment_service_server::PaymentService, ProcessPaymentRequest, ProcessPaymentResponse,
};

/// Implements the `PaymentService` gRPC trait generated by tonic.
#[derive(Debug, Clone)]
pub struct PaymentHandler {
    pool: Pool,
}

impl PaymentHandler {
    pub fn new(pool: Pool) -> Self {
        Self { pool }
    }
}

#[tonic::async_trait]
impl PaymentService for PaymentHandler {
    /// Processes a payment request, records it in the `payment` table,
    /// and returns a success/failure response.
    async fn process_payment(
        &self,
        request: Request<ProcessPaymentRequest>,
    ) -> Result<Response<ProcessPaymentResponse>, Status> {
        let req = request.into_inner();

        // ── Validation ───────────────────────────────────────────────────────
        if req.order_id.trim().is_empty() {
            return Err(Status::invalid_argument("order_id is required"));
        }
        if req.amount <= 0.0 {
            return Err(Status::invalid_argument("amount must be greater than zero"));
        }
        if req.currency.trim().is_empty() {
            return Err(Status::invalid_argument("currency is required"));
        }

        let order_id: Uuid = req.order_id.parse().map_err(|_| {
            Status::invalid_argument(format!("order_id '{}' is not a valid UUID", req.order_id))
        })?;

        info!(
            order_id = %order_id,
            amount   = req.amount,
            currency = %req.currency,
            "Processing payment"
        );

        // ── Persist payment record ───────────────────────────────────────────
        let client = self.pool.get().await.map_err(|e| {
            error!("DB pool error: {}", e);
            Status::internal("database unavailable")
        })?;

        // Generate a deterministic-looking transaction ID for demonstration.
        // In production this would come from the payment gateway (Razorpay, Stripe …).
        let transaction_id = Uuid::new_v4().to_string();

        let stmt = client
            .prepare_cached(
                r#"
                INSERT INTO payment (
                    checkout_session_id,
                    gateway,
                    transaction_id,
                    status,
                    amount,
                    currency,
                    paid_at
                )
                VALUES (
                    $1::uuid,   -- checkout_session_id (re-using order_id as placeholder)
                    'internal', -- gateway
                    $2,         -- transaction_id
                    'captured', -- status
                    $3,         -- amount
                    $4,         -- currency
                    NOW()       -- paid_at
                )
                RETURNING id
                "#,
            )
            .await
            .map_err(|e| {
                error!("Failed to prepare statement: {}", e);
                Status::internal("database error")
            })?;

        let row = client
            .query_one(&stmt, &[&order_id, &transaction_id, &req.amount, &req.currency])
            .await
            .map_err(|e| {
                error!("Failed to insert payment: {}", e);
                Status::internal(format!("failed to record payment: {}", e))
            })?;

        let payment_id: Uuid = row.get("id");
        info!(payment_id = %payment_id, transaction_id = %transaction_id, "Payment recorded");

        Ok(Response::new(ProcessPaymentResponse {
            success: true,
            transaction_id,
        }))
    }
}
